name: cicd

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  ci-cd:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Save SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > windows.pem
        echo icacls windows.pem /grant "%USERNAME%:F" /inheritance:r
      
    - name: Set SSH key file permissions
      run: echo %USERNAME%
    
