name: cicd

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  ci-cd:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: make connection and pull
      run: |
        icacls "/windows.pem" /grant "%USERNAME%:(OI)(CI)F" /t /q
        ssh -i "/windows.pem" ubuntu@ec2-13-235-70-140.ap-south-1.compute.amazonaws.com


